[package]
name = "datdot-node"
version = "2.0.0-rc3"
edition = "2018"
authors = ['Joshy Orndorff', '4meta5', 'Jimmy Chu']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = 'An instant-sealing Substrate node for datdot. Based on the substrate kitchen-node.'
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"Node",
	"Instant Seal",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc3"

[[bin]]
name = "kitchen-node"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.3.1"
structopt = "0.3.8"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.2.0"
parking_lot = "0.9.0"
trie-root = "0.15.2"
sc-basic-authorship = '0.8.0-rc3'
sc-cli = '0.8.0-rc3'
sc-client-api = '2.0.0-rc3'
sc-consensus = '0.8.0-rc3'
sc-consensus-manual-seal = '0.8.0-rc3'
sc-executor = '0.8.0-rc3'
sc-network = '0.8.0-rc3'
sc-service = '0.8.0-rc3'
sc-transaction-pool = '2.0.0-rc3'
sp-consensus = '0.8.0-rc3'
sp-core = '2.0.0-rc3'
sp-inherents = '2.0.0-rc3'
sp-io = '2.0.0-rc3'
sp-runtime = '2.0.0-rc3'
sp-timestamp = '2.0.0-rc3'
sp-transaction-pool = '2.0.0-rc3'

# This node is compatible with any of the runtimes below
# ---
# Common runtime configured with most Recipes pallets.
runtime = { package = "datdot-runtime", path = "../runtime" }

# Runtime with custom weight and fee calculation.
# runtime = { package = "weight-fee-runtime", path = "../../runtimes/weight-fee-runtime"}

# Runtime with off-chain worker enabled.
# To use this runtime, compile the node with `ocw` feature enabled,
#   `cargo build --release --features ocw`.
# runtime = { package = "ocw-runtime", path = "../../runtimes/ocw-runtime" }

# Runtime with custom runtime-api (custom API only used in rpc-node)
# runtime = { package = "api-runtime", path = "../../runtimes/api-runtime" }
# ---

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = '2.0.0-rc3'

[features]
ocw = []
